### ISSUE TITLE
MYMETA should not be included

### ISSUE THREAD

**Issue by chorny** [hoytech/String-Compare-ConstantTime#3]
Your distribution (FRACTAL/String-Compare-ConstantTime-0.310.tar.gz) contains files MYMETA.yml and/or MYMETA.json. These files should not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is about old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=FRACTAL and contact me.

**Comment by hoytech** [comment]
Will be gone next release: d98e9d6e696c54ca3c42d4a733727eca0fa9353b

Thanks!

**Comment by hoytech** [comment]
.... and here is that release:

https://metacpan.org/release/FRACTAL/String-Compare-ConstantTime-0.311

:)
